export const FormData = {
  formStyles: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 15,
  },
  formData: [
    {
      type: "text",
      label: "Search",
      placeholder: "Enter the Search",
      required: true,
      name: "search",
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },
    {
      type: "name",
      label: "Name",
      placeholder: "Enter the name",
      required: true,
      name: "Name",
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },
    {
      type: "radio",
      label: "Radio",
      placeholder: "Enter the value",
      required: true,
      name: "Radio Select",
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },
    {
      type: "email",
      label: "Email",
      placeholder: "Enter the value",
      required: true,
      name: "Email",
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },
    {
      type: "password",
      label: "Password",
      placeholder: "Enter the Password",
      required: true,
      name: "Password",
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },
    {
      type: "password",
      label: "Confirm Password",
      placeholder: "Enter the Confirm Password",
      required: true,
      name: "Confirm Password",
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },
    {
      type: "number",
      label: "Mobile Number",
      placeholder: "Enter the Mobile Number",
      required: true,
      name: "Mobile Number",
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },
    {
      type: "file",
      label: "Upload",
      placeholder: "Upload",
      required: true,
      name: "Upload File",
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },
    {
      type: "data",
      label: "Date",
      placeholder: "Enter Date",
      required: true,
      name: "Date",
      algin: "column",
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },
    {
      type: "color",
      label: "Color",
      placeholder: "Enter Color",
      required: true,
      name: "Color",
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },

    {
      name: "gender",
      label: "Gender",
      type: "select",
      options: [
        { key: "male", value: "Male" },
        { key: "female", value: "Female" },
        { key: "other", value: "Other" },
      ],
      required: true,
      style: {
        width: "100%",
        padding: "8px",
        border: "1px solid #ccc",
        borderRadius: "4px",
      },
      labels: {
        color: "pink",
        fontSize: "16px",
        fontWeight: "500",
        marginRight: "4px",
      },
      errorMessage: "First name is required.",
    },
  ],
};
